### ISSUE TITLE
MQL query exception

### ISSUE THREAD

**Issue by ocervell** [googleapis/python-monitoring#125]
Trying to run a simple query using the SDK after MQL support was added:

```
def test_mql_expression(mql_query):
    client = QueryServiceClient()
    project = f'projects/{PROJECT_ID}'
    request = QueryTimeSeriesRequest(name=project, query=str(mql_query))
    result = client.query_time_series(request)
    print(result)
    return result
```

```
test_mql_expression('fetch global::custom.googleapis.com/metric_test')
```

Getting the following exception:
```
Traceback (most recent call last):
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "One or more errors parsing the query."
        debug_error_string = "{"created":"@1618853686.419251000","description":"Error received from peer ipv6:[2a00:1450:4007:807::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"One or more errors parsing the query.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ocervello/.virtualenvs/sabre/bin/promql-convert", line 33, in <module>
    sys.exit(load_entry_point('promql-to-mql', 'console_scripts', 'promql-convert')())
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/click-8.0.0rc1-py3.8.egg/click/core.py", line 1041, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/click-8.0.0rc1-py3.8.egg/click/core.py", line 971, in main
    rv = self.invoke(ctx)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/click-8.0.0rc1-py3.8.egg/click/core.py", line 1309, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/click-8.0.0rc1-py3.8.egg/click/core.py", line 715, in invoke
    return callback(*args, **kwargs)
  File "/Users/ocervello/Workspace/dev/promgrafana-cloudops/promql_to_mql/cli.py", line 164, in convert
    result = test_mql_expression(expression)
  File "/Users/ocervello/Workspace/dev/promgrafana-cloudops/promql_to_mql/test.py", line 51, in test_mql_expression
    result = client.query_time_series(request)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/google/cloud/monitoring_v3/services/query_service/client.py", line 381, in query_time_series
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/ocervello/.virtualenvs/sabre/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 One or more errors parsing the query.
```

Note that this query works in the Metrics Explorer Query editor, so not sure what's going on here.

**Comment by ocervell** [comment]
Nevermind, API-side error
