### ISSUE TITLE
504 DeadlineExceeded - create_time_series

### ISSUE THREAD

**Issue by fancybear-dev** [googleapis/python-monitoring#321]
Hi,

We use a GCP Cloud Function to ingest data into a custom metric. This function has been creating vast amounts of consistent errors, like you can see below. The data does get ingested, but the function ends up in this error. As far as we know, this is either an API issue at Google or a bug somewhere in this library. 

We can't share the full code base that is being executed, but here is the function in question + the exact error it produces.

#### Code example

```python
def ingest_metric_to_gcp(active_agents, project, metric):
    client = monitoring_v3.MetricServiceClient()
    project_name = f"projects/" + project

    series = monitoring_v3.TimeSeries()
    series.metric.type = "custom.googleapis.com/" + metric
    now = time.time()
    seconds = int(now)
    nanos = int((now - seconds) * 10 ** 9)
    interval = monitoring_v3.TimeInterval(
        {"end_time": {"seconds": seconds, "nanos": nanos}}
    )
    point = monitoring_v3.Point({"interval": interval, "value": {"double_value": active_agents}})
    series.points = [point]
    client.create_time_series(name=project_name, time_series=[series])
```

#### Stack trace
```
 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 89, in main
    ingest_metric_to_gcp(active_agents, PROJECT, METRIC)
  File "/workspace/main.py", line 43, in ingest_metric_to_gcp
    client.create_time_series(name=project_name, time_series=[series])
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/monitoring_v3/services/metric_service/client.py", line 1125, in create_time_series
    rpc(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline expired before operation could complete.
```
```
 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: 
```

**Comment by fancybear-dev** [comment]
This is how the import looks like;
```
from google.cloud import monitoring_v3, secretmanager
```

**Comment by parthea** [comment]
Hi @fancybear-dev,

Please could you try setting the timeout parameter of [create_time_series](https://cloud.google.com/python/docs/reference/monitoring/latest/google.cloud.monitoring_v3.services.metric_service.MetricServiceClient#google_cloud_monitoring_v3_services_metric_service_MetricServiceClient_create_time_series) to see if that helps resolve the error `504 Deadline expired before operation could complete`?

**Comment by fancybear-dev** [comment]
Will try it out today! Thanks for your suggestion.

**Comment by parthea** [comment]
The timeout needs to be increased further.
change
`client.create_time_series(name=project_name, time_series=[series], timeout=60)` to `client.create_time_series(name=project_name, time_series=[series], timeout=120)` or `client.create_time_series(name=project_name, time_series=[series], timeout=240)` to allow more time for the operation to complete. I'm going to close this issue but please feel free to re-open it with more information
